# Generated by Django 5.2.1 on 2025-05-07 19:34

import django.db.models.deletion
import walking_routes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'route category',
                'verbose_name_plural': 'route categories',
            },
        ),
        migrations.CreateModel(
            name='WalkingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=walking_routes.models.route_image_upload_path, verbose_name='main image')),
                ('transport_type', models.CharField(choices=[('walking', 'Walking'), ('public', 'Public Transport'), ('mixed', 'Mixed')], default='walking', max_length=10, verbose_name='transport type')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='distance (km)')),
                ('estimated_time_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='estimated time (min)')),
                ('gpx_file', models.FileField(blank=True, null=True, upload_to='gpx_files/', verbose_name='GPX file')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walking_routes', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='routes', to='walking_routes.routecategory')),
            ],
            options={
                'verbose_name': 'walking route',
                'verbose_name_plural': 'walking routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('image', models.ImageField(blank=True, null=True, upload_to=walking_routes.models.point_image_upload_path, verbose_name='image')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='walking_routes.walkingroute')),
            ],
            options={
                'verbose_name': 'route point',
                'verbose_name_plural': 'route points',
                'ordering': ['order'],
            },
        ),
    ]
